services:
  api:
    image: ${TUWATCH_SERVER_IMAGE:-snowballons/tukiwatch-server:1.0.6}
    ports:
      - "8000:8000"
    environment:
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}
    env_file:
      - path: .env
        required: false
