name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          persist-credentials: false 
          submodules: true    # If your site uses submodule, make sure to set it to 'true'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          # The following will remove all files from the gh-pages branch before deploying.
          # This is useful if you want to ensure that old files are removed.
          force_orphan: true 
